# This file is uses to configure any hardware specific things for the sway wm
# such as reversing the touchpad scroll direction
# this file will be sym linked into /etc/nixos/programs/sway
# and then read by the home-manager sway config in order to apply the changes

input "type:touchpad" {
    natural_scroll enabled
    middle_emulation disabled
}
